# Generated by Django 4.0.6 on 2022-07-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_step',
            new_name='preparation_steps',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_step_is_html',
            new_name='preparation_steps_is_html',
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(default='', max_length=65),
            preserve_default=False,
        ),
    ]
